### ISSUE TITLE
Support of nflx-genie-client for python 3

### ISSUE THREAD

**Issue by rajeshkatkarnice** [Netflix/genie#1003]
Hi Team , 
can we use the nflx-genie-client for our python 3 stack. If yes, which release version we should use 
It is working fine with python 2.7 version.

**Comment by tgianos** [comment]
Hey @rajeshkatkarnice I believe at least the latest release should work with Python 3 as that `pygenie` is re-wrapped internally into a larger library that's uses Python 3.

You'll probably have better luck asking this question over at the [Pygenie](https://github.com/Netflix/pygenie/issues) repo so that the maintainers can respond. It looks like someone already asked about [Python 3](https://github.com/Netflix/pygenie/issues/59) so I'll have the team look at it

**Comment by tgianos** [comment]
@rajeshkatkarnice @cabhishek just released a new version of `pygenie` with the metadata updated to support python 3. Should be version [3.3.16](https://github.com/Netflix/pygenie/releases/tag/3.6.16)
