### ISSUE TITLE
Does genie supports Spark K8S operator?

### ISSUE THREAD

**Issue by bowenli86** [Netflix/genie#1044]
Hi there,

We are considering to use genie as gateway to our spark cluster. The Spark cluster is on K8S, and thus we are considering to use Spark operator like https://github.com/GoogleCloudPlatform/spark-on-k8s-operator.

Does genie supports Spark K8S operator?

Thanks

**Comment by mprimi** [comment]
Hello @bowenli86 

I am not deeply familiar with the difference between Spark vs. Spark K8S. 
If you could elaborate on how K8S is different and why you doubt it will work, I can probably provide some more details.

But I think the answer is yes. Genie could work.
Genie is agnostic to Spark and can be used for any kind of "job" execution, whatever "job" is, and you get to decide. As Genie administrator, you need to model and create the the resources in a way that fits what you want to do.

If you search the Genie codebase, you'll find no mention of Spark outside of the demo/example folders.
That's because there is no Spark-specific logic, nor any other kind of technology specific logic for what's downstream of Genie.

At Netflix, Genie is used for Spark, but also for a variety of other Big Data engines, tools, frameworks, data-stores, etc.
The future will bring new tools. As long as their owner register them in Genie correctly, they become conveniently usable by any user or application that is able to submit a Genie jobs request via Genie client or other REST client.
