### ISSUE TITLE
Considerations for distributed deployment (storage & addressing)

### ISSUE THREAD

**Issue by lindblombr** [Netflix/genie#1048]
Hi Genie team!  I've been evaluating Genie on K8S and wanted to pick expert brains on a few things I've found in my travels.  

First, though, I want to say: what a fantastic tool!  It's really clear very quickly how powerful this type of abstraction is atop a number of different systems.

1. Given a distributed deployment of Genie (say, a K8S stateful set), would it be more appropriate to attach ReadWriteOnce or ReadWriteMany storage to the Genie pods?  Its a bit difficult without diving further into the code to understand whether the storage layer for jobs/archives/attachments/cache should be shared among all instances of a Genie deployment or if Genie is capable of proxying requests to appropriate instances.  I'm testing both approaches, but would greatly appreciate expert feedback.

2. It seems that there is some "state" that persists beyond a Genie deployment when backed by a RDBMS.  Proxy request errors pop up for old instances that have been cycled out or replaced by rolling restarts or other maintenance activities.  I think these two problems (storage and addressing) end up being related in this case.  I wasn't quite able to extract this information from the docs, but before we test further, I'm curious what Genie expects in terms of "host persistence".

Thanks in advance!

**Comment by mprimi** [comment]
Hello Brian, 

Genie provides a number of injection points so the answer to a lot of these questions is: "it depends on your deployment/environment/configuration".

The deployment model for Genie V3 (current stable release, but not actively developed) is the following:
 -  A set of genie nodes are deployed behind a load balancer and share RDBMS where most of the state is kept
 - Most requests (e.g., say job status) can be answered by any node (by looking up state in the DB)
 - Job submission lands on a random node, and the job is executed on that same host

So for example attachments are stored locally on disk, because that's where they are used by the job once it starts.
Requests for output of a _running_ job are automatically forwarded from one genie node to the node running the job. Same for 'kill' requests.

Job outputs may be available to any genie host after the original host is gone IF they were archived somewhere else.
Genie comes with a default archiver that backs them up on S3, but a different archiver implementation should be easy to implement and plug-in, if S3 doesn't work for you.

Other components can similarly be replaced or disabled entirely.


We've been working for quite some time on Genie V4 (still in active development, but stable enough for us to use internally).
The primary architectural difference between V3 and V4 is that V4 removes the assumption that jobs are running on one of the cluster nodes.

We're moving to a model where Genie nodes are stateless (still sharing the RDBMS), and each job is executed in it's own remote container.
This currently open PR for example, allows multiple job launchers and a script plug-in to dynamically control which launcher is used.
For example, you may want to run some jobs in "legacy" mode (on the same host, as Genie V3), while other jobs can be spun out into dedicated containers.
Moreover, submitting via REST API is no longer the only way to initiate a job: you can now also execute via command-line by using the Genie agent directly. This allows running jobs outside of the Genie cluster (e.g, on your laptop), while still leveraging all the other features (cluster/command resolution, access to logs, remote kill, etc).

Genie V4 documentation is still lacking, but it's on my radar for this month, as we're getting closer and closer to releasing v4.0.0.

Let me know if this answered your questions, or if you have follow up ones.

**Comment by lindblombr** [comment]
This is super useful information, and I'm definitely interested in the new job launcher model.  I'll need to poke around to understand it a bit better (as in, will Genie act as a K8S client to create new pods which are containers executing the desired commands?).  S3 storage for archives is actually quite sufficient, and your explanation clears this up for me quite nicely.  Is the vision for archives that, upon _job_ container tear-down, archiving will take place and that, during job runtime, the container will serve those contents to Genie to handle client requests?

Big thanks for the response.

**Comment by lindblombr** [comment]
Also, not sure if there is a k8s roadmap, but perhaps in such a deployment model, the launcher would deploy `GenieJob` spec resources and that a `GenieController` handles the ins-and-outs of orchestrating pods that run the job commands.  A controller could be helpful in other respects, too, to manage lifecycle of genie web tasks (if necessary).  Again, not being privy to the community or internal direction of the project, I don't know if this has already been discussed :)

**Comment by mprimi** [comment]
> as in, will Genie act as a K8S client to create new pods which are containers executing the desired commands?

Yes, you can create your own `AgentLauncher` which spawns a container in which a job is executed. We do not plan to bundle support for K8S, but we use [Titus](https://netflix.github.io/titus/) internally which is similar.

> Is the vision for archives that, upon job container tear-down, archiving will take place and that, during job runtime, the container will serve those contents to Genie to handle client requests?
Yes. 
In Genie V4 every job is executed by an agent. The agent lifecycle (omitting non-relevant details) is:
 - Retrieve job information
 - Start and monitor job (during this time, if you request a file via API, the request will automatically be routed to the agent)
 - Archive the job files

> Also, not sure if there is a k8s roadmap (...)
We're not planning to support K8S, but we're always trying to make Genie flexible enough to be deployed in a variety of environments, ranging from K8S to your own laptop and everything in between.
In your specific case, I think you can plug-in the launcher abstraction, and also provide other beans such as the controller you described.

**Comment by mprimi** [comment]
[This PR](https://github.com/Netflix/genie/pull/1054) adds the Titus agent launcher i mentioned earlier.

Adding a similar launcher for K8s should be similarly easy.
