### ISSUE TITLE
How to determine the value of genie.server.max.running.jobs

### ISSUE THREAD

**Issue by JoeReid-Korrelate** [Netflix/genie#111]
Hello,

We currently run a single genie instance to support a relatively small hadoop cluster.  We recently started getting 503's and tracked the issue to exceeding the number of max running jobs set in genie.properties.  The default is set to 30, after which the [Genie customization docs](https://github.com/Netflix/genie/wiki/Customization-and-Options) start talking about using Eureka and multiple instances of Genie.

From **genie.properties:**
`com.netflix.genie.server.max.running.jobs=30`

The long-term goal is to pull in Eureka or a tool like it, but for our current use case we're really interested in how this default is determined and if we can get more mileage out of a single node.

For single-instance deployments of Genie, how far does genie server scale with hardware (more RAM, CPU, etc).  What are the variables?

Regards,
Joe Reid

**Comment by amitsharma1981** [comment]
Hello,

The default is determined from the property you mentioned in you email.
That along with a few other properties in genie.properties controls the
number of jobs. Genie is not aware of the characteristics of the jobs that
it runs. So it does not have statistics like Memory, CPU etc. You as an
admin need to figure out what is a typical workload for your job and based
on the resources available on the genie node, how many can it run
concurrently. For example, at Netflix the metric we focus on is 1.5GB of
jvm size per client process. So if we have 30GB of memory, we leave aside
some for system processes and allocate around 22.5GB for Genie jobs. So we
set the max running jobs to 15.

Hope this helps.

Thanks,
Amit

On Mon, Mar 16, 2015 at 8:38 AM, JoeReid-Korrelate <notifications@github.com

**Comment by tgianos** [comment]
Hi Joe,

As Amit said currently Genie doesn't force any restrictions on the forced child processes. We have plans in the future to change how jobs are executed and this may be a feature we introduce at that time. 

Setting that ```com.netflix.genie.server.max.running.jobs``` property is your first step but since you're running in a single node instance you should also set ```com.netflix.genie.server.forward.jobs.threshold``` to be a number higher than ```com.netflix.genie.server.max.running.jobs```. This will disable job forwarding and just start rejecting jobs if your node is overwhelmed.

We've never tried to run a ton of jobs on a single Genie node so can't speak to how it will perform if you place it on one huge piece of hardware and crank up the jobs to a large number. We suspect it will work but it's not a use case we currently have. We run ~30 jobs per Genie node internally.

Hope this helps.

Also as an FYI it's probably better to ask questions in the [Genie Google Group](https://groups.google.com/forum/#!forum/genieoss) in the future so others can see answers and they're not lost in Github Issues.

Thanks,
Tom

**Comment by JoeReid-Korrelate** [comment]
@tgianos @amitsharma1981 - Great, thanks guys!  I appreciate your help.
