### ISSUE TITLE
Feature Request:  Enable IAM role authentication.

### ISSUE THREAD

**Issue by Joseph-R** [Netflix/genie#178]
Hello,

In the notes for Genie 2.2, I see [documentation]( https://github.com/Netflix/genie/wiki/Customization-and-Options#aws-keys) on how to manage and configure AWS keys for Genie.

I'm not sure if this is the right place, but I would like to request IAM role-based authentication if possible for Genie 3.  This would help users conform to [AWS best practices](http://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html) for identity and access management.  

*  I think this could be accomplished easily if your team plans to support Hadoop 2.6+
*  Hadoop supports role-based authentication with the s3a protocol as of [HADOOP-10400](https://issues.apache.org/jira/browse/HADOOP-10400).  
* `fs.s3a.access.key` and `fs.s3a.secret.key`can simply be omitted for role-based auth.  Which means that users could simply provision an EC2 instance under the correct role and be good to go.

Regards,
Joe Reid

**Comment by amitsharma1981** [comment]
Hi Joseph,

Genie 1 and 2 both relied on using Hadoop as the mechanism to copy down the dependencies from S3. Going forward in Genie 3 we are going to implement a pluggable FileCopy interface that will be responsible for copying down files. We already plan to add support of IAM roles to an implementation of this interface to deal with S3. This should pretty much implement the feature you are requesting in this issue. 

On a separate note , since the copying of dependencies is a part of the bash script today in Genie 2, you can always tweak it and use your own script to do this. Thats exactly what we do within Netflix. We have file copy script that uses IAM roles. We update the joblauncher.sh script to use our file copy script instead of hadoop copy commands.

**Comment by Joseph-R** [comment]
@amitsharma1981 - Great, good to know!   Thanks.
