### ISSUE TITLE
Features of genie3

### ISSUE THREAD

**Issue by mhvijay** [Netflix/genie#369]
We are planning to upgrade to genie3 . Could you please let us know the place where we can find genie3 new features

**Comment by tgianos** [comment]
Hi @mhvijay,

Genie 3 OSS isn't fully released yet. Mostly because we haven't gotten a chance to work on documentation yet as we work through anything found at scale internally.

As such we don't have a filtered down list of the primary features (security, new data model, new API's, etc) yet.

You can find a comprehensive list of everything that's been done towards Genie 3 here:
https://github.com/Netflix/genie/milestone/7?closed=1

A few of us internally are out on vacation through mid-September but hope to start working on documentation after that with a hopeful OSS release date sometime in October.

Let us know if that helps or if you have any questions in the mean time.

Tom
