### ISSUE TITLE
Genie jobs fail with: Job d75befc0-619a-11e7-b9c0-06e23ce966f0 can't run on this node 92160/92160 MB are used and requested 1024 MB

### ISSUE THREAD

**Issue by jelez** [Netflix/genie#549]
We use ELB to send tasks to a cluster of Genie nodes. We also use zookeeper for leader election.
We have set genie.jobs.memory.maxSystemMemory to about 80% of the memory of the instance == 92160MB.
We currently experience a big issue with load distribution which causes alot of tasks to fail:
We have 3 instances and we calculate based on the maxSystemMemory setting that around 90 tasks 1GB each can be executed per server for a total of 270 concurrent jobs in all on the cluster.
However, we observe a huge skew in load and alot of job failures and we are not ableto saturate the cluster - of the 3 instances 1 runs 90 jobs and the rest run around 10 jobs each; jobs on the instance with 90 jobs fail with error:

```
Job d75befc0-619a-11e7-b9c0-06e23ce966f0 can't run on this node 92160/92160 MB are used and requested 1024 MB
```

ELB tries round-robing but it does not necessarily guarantee it, also it gets no load feadback from the workers.
What settings do you use to ensure that the load across genie instances is evenly distributed?

**Comment by tgianos** [comment]
@jelez this is definitely a drawback of the Amazon classic ELB's in that they round robin all HTTP traffic. We're thinking about looking at ALB to see if they provide more functionality.

If you wanted true intelligence at the load balancer you'd have to put some smart routing component in front of Genie like nginx or something to route the POST's evenly. Even then though due to the nature of some jobs running longer than others it might not be perfect.

What we do is rely on the Genie health reporting. Have you tied this into the Load Balancer?
here is our load balancer configuration for the health check:

```
Ping Target | HTTP:{yourPortHere}/actuator/health
Timeout | 5 seconds
Interval | 10 seconds
Unhealthy threshold | 2
Healthy threshold | 2
```
Genie ships with health indicators that track the amount of available memory left and will mark the node out of service once it can't run 1 more max memory job (by default 10 GB). So when this happens the Genie node will return a non-2xx code from the `/actuator/health` endpoint and the ELB will stop sending ALL requests to that node.

Additionally we (using [atlas](https://github.com/Netflix/atlas) and cloudwatch) track the average memory used across the cluster. When the average memory used is ~60% of the cluster max memory configuration we begin scaling the Genie cluster.

These two mechanisms keep us from running into the situation you're describing. While certain nodes still can become unbalanced they will eventually stop taking on new jobs allowing the other nodes to take load till some burns off the busy node.

Hope that helps. Let us know if you have more questions about this.

**Comment by jelez** [comment]
Thanks Tom, that makes sense. I missed the /actuator/health check - I am currently doing regular http check. Let me try this. I think we can close this issue at this time.
