### ISSUE TITLE
anybody help me??????

### ISSUE THREAD

**Issue by hujisan** [Netflix/genie#663]
I have question about the genie diagram ,why use Eureka in genie???when job is finished ,we could shut down EMR YARN cluster to  save money ,if we let the EMR cluster stand by ,we shoud pay more money to AWS.Is there any other reason to let the EMR cluster stand by ?

**Comment by tgianos** [comment]
@hujisan what diagram are you referencing? Current iterations of Genie do not use Eureka explicitly.

As for you EMR standby question it sounds like your workflow is to launch one cluster per job. In that case there is no reason to leave the cluster running as you say. Just tear it down and mark it `TERMINATED` in Genie. However if you use one cluster for many jobs it's perfectly reasonable to leave it running to save time on startup, etc.

**Comment by hujisan** [comment]
Hi tgianos,Thanks very much for you reply
Here is the url of the diagram,https://netflix.github.io/genie/images/2/architecture.png,there is a Eureka Service in the diagram .
In our case,we launch one cluster per workflow,when all the jobs of the workflow are finished ,we shut it down.we have many workflows running in different times every day.however there could be  serveral hours between two workflows when no workflow is running.

**Comment by mprimi** [comment]
@hujisan that image is referenced from Genie V2 documentation, it is quite old. 
Genie V3 works differently and it's the recommended stable version since last year, I'd recommend checking that out: https://netflix.github.io/genie/releases/3.2.5/
Eureka is an optional component and it's disabled by default. If you enable it, servers will register and can be discovered through it.

To your second point. Genie can work for this kind of process:
1. Launch a cluster
2. Register the cluster with Genie
3. Run a sequence of jobs (i.e. a workflow) on the cluster via Genie
4. Mark the cluster terminated in Genie (so no jobs get routed to it)
5. Shut down the cluster

Steps 1 and 5 are outside of Genie scope, i.e. they are your responsibility. 
Genie does not create/destroy the cluster for you, nor it prevents you from creating/destroying it.
