### ISSUE TITLE
Using Genie to run Spark on EMR

### ISSUE THREAD

**Issue by mors1** [Netflix/genie#726]
Hi,

We want to use Genie to run Spark on our AWS EMR cluster. From what I understand, Genie is supposed to be agnostic to the environment it runs in. 

How does that happen with Spark? 

Spark needs to be installed on every node in the EMR cluster. Does Genie install the version it runs of Spark on the EMR prior to each run? 
Also - AWS makes modifications to the installation of Spark in the EMR, so features such as EMRFS don't exist in the repositories that are available to download from Apache. 

I know that you use Genie for this purpose in Netflix, how do you handle these issues? 

Thanks in advance, 
Mor

**Comment by mprimi** [comment]
Hello Mor,
we don't use Genie to deploy and manage clusters (although there's nothing stopping you from doing so).
Our clusters are created by other automation/tools. A step of creating a cluster and making it available, is to register it in Genie as resource.

What we use Genie for w.r.t. Spark is the *driver* side. 
Our users submit a query *Q* via genie without having to worry about details that are not relevant to them, e.g, they can say "Execute query **Q** with **Spark** in **test** with **production** data". Genie takes this "high level" description and figures out all the nitty-gritty details: which cluster to target, which version of Spark to use, where to obtain the correct binaries and configuration files, which security roles to apply, which memory settings to use... and more. It sets everything up so that *Q* can be executed on behalf of the user and without exposing them to these low-level details.

Does this answer your question

**Comment by rdblue** [comment]
I can shed a little more light on what we do for Spark. Marco is right that we localize the Spark application, which could be one of several supported versions.

I think Mor wants to know how we run executors for that application. For that, we use Spark's ability to ship its own libraries as an archive that will get unpacked by YARN on each NodeManager. So basically, Spark adds its Jars to the distributed cache, which gets localized on each node to start executors. That way our versions always match.

We've also made a couple modifications to Spark so that the archive we add to the distributed cache has no timestamp and always uses the same order for Jars. This is to get a consistent hash for each build or version. Then we use that hash to get a well-known location in HDFS that we use for the distributed cache. We also mark the archive as public and only upload it once. By doing that, NodeManagers will recognize that the archive is shared across Spark versions and has not changed, so it will cache the archive for faster container localization.

**Comment by mors1** [comment]
Thank you Ryan and Marco, this information is very helpful.
