### ISSUE TITLE
Yarn Application ID not retuned when via Job is Submitted via Post or getStatus

### ISSUE THREAD

**Issue by Gelesh** [Netflix/genie#983]
When a Job is posted to Yarn via` Post '/api/v3/jobs' `end point, or the status of job is checked via G`ET /api/v3/jobs/{id} ` _(where this {id} is Genie Job ID_) , **Yarn Application ID** is not returned.
If Yarn Id is also returned, it makes easier to investigate Job Failing on the Yarn Side.

**Comment by mprimi** [comment]
Hello @Gelesh, the job URL and job id are returned in the `Location` header of the response

```
> POST /api/v3/jobs HTTP/1.1
> Content-Type: application/json
> Accept: application/json
>
< HTTP/1.1 202
< Content-Length: 0
< Date: Thu, 07 May 2020 19:46:07 GMT
< Location: https://genie.test.netflix.net/api/v3/jobs/b4fd6843-11b6-4c2f-a5a3-a76d758cb427
<
```

This is documented here: https://netflix.github.io/genie/docs/4.0.0-rc.52/rest/#_submit_a_job

**Comment by mprimi** [comment]
@Gelesh, i completely misunderstood your comment, you're not looking for the job id, but some other ID generated by the command itself when it runs (in your case, a Yarn ID).

Genie is unaware of what the actual job does, it's just following "instructions" (in the form of command/application/cluster configurations).

My suggestion would be for your command/job to create a file containing metadata (such as the Yarn ID or URL) and then fetch this file through the API via something like: `https://my.genie.net/file/<job_id>/output/yarn-metadata.json`

**Comment by Gelesh** [comment]
@mprimi  Thanks For responding. You could see that the `LocalJobRunner `generated a fetches out a Process ID from the Cluster. And later  `JobPersistanceServiceImpl `saves t`o DB via JPA.`.
That Process ID, I suppose its same as Yarn ID, when its a Yarn manged Cluster.
This is not returned on jobSubmit, or getJobStatus Endpoints. Nor we have any endpoint dedicated to facilitate respond back the Cluster Process ID  , although that information is stored in DB.
Not Even, Any DeBug Log spits that out.
Appreciate if some one could fix that in next release.

**Comment by tgianos** [comment]
Hi @Gelesh. The process id you're referring to is not yarn id that you originally asked for. That process id is the process id of the underlying bash run script Genie launches. It has no sense of what the underlying process is doing. Yes it is stored in the database and can already be accessed via [this API](https://netflix.github.io/genie/docs/4.0.0-rc.52/rest/#_get_a_job_execution) in the `processId` field.

Just to be clear though this will only give you a pointer to the process on a Genie box not on the underlying process cluster which we purposely avoid tight coupling for.

**Comment by Gelesh** [comment]
@tgianos  .. Thanks for Clarifying.  And as you said, "That process id is the process id of the underlying bash run script Genie launches" and has noting to do with Yarn ID.
Please educate me on , getJob Status, etc would look for the executing Job, It would be referring YarnID or Equivalent somehow to pull out the status and Logs of the Yarn Jobs.  
Is there any API which exposes that applicationID some where

**Comment by tgianos** [comment]
@Gelesh The `getJobStatus` call returns the job status as Genie knows about it within the lifecycle of a Genie job which is purposely abstracted from the underlying job process. A Genie job may be in status `RUNNING` however on an underlying Hadoop cluster the yarn job is in status `ACCEPTED` due to being in some queue waiting for resources. Since Genie only monitors the client process to any job it only returns the information it can, that is that the client process is currently running.

There is no Genie API which exists to get the yarn id as this would necessitate us tightly coupling to YARN which we purposely don't do as Genie is designed to run any kind of job that can be modeled using the available cluster/command/application semantics.

There could be several ways to get the application id if you so desire. If you control the deployment code for your yarn applications you could so as @mprimi suggested and have them write out a file into the job directory containing the application id and then read it back using the `api/v3/jobs/{id}/output/*` API.

Internally at Netflix we separate these concerns as Genie is responsible for orchestrating and executing the jobs but we have another service which inspects the output files from a job (`stdout`, `stderr`, etc) and pulls relevant information (such as the yarn application urls if applicable). This allows Genie to focus on what it does well and this other service focusses just on parsing out important information to present to other systems such as endpionts.
